### ISSUE TITLE
Rational values for scene coordinates 

### ISSUE THREAD

**Issue by Fynx** [Fynx/BTech#10]
Using QPoints for storing scene coordinates is a rather poor idea. Not only it's incompatible with Qt libraries, a scene coordinate function can be easily mistaken with a game-system one.

**Comment by szreder** [comment]
Work in progress in dev branch: use Coordinate class for game-system coordinates, use QPointF instead of QPoint for scene objects' positions.

**Comment by szreder** [comment]
Work completed in dev branch. Waiting for ACK.

**Comment by szreder** [comment]
Resolved in:
99427c56c6c2f1e84015535776f16a8104b3906f
8a9f2b59784031a3410e365cce1f944968fa885a
