### ISSUE TITLE
Two CombatAction types

### ISSUE THREAD

**Issue by szreder** [Fynx/BTech#18]
src/BTCommon/Action.h:67:class CombatAction : public Action {

src/BTCommon/Utils.h:258:    enum class CombatAction : quint8 {

**Comment by Fynx** [comment]
It looks what does it look like: a CombatAction and a CombatActionType. The true problem is the Action->CombatAction relation, which enforces to use pointers instead of objects. This is most unnatural in this case - and quite dangerous. Still thinking about it.

**Comment by Fynx** [comment]
Resolved in commit 00da1d4dde6bfb8864ba9b88ec0304d79c622876
