### ISSUE TITLE
GraphicsMap inheriting from Map

### ISSUE THREAD

**Issue by Fynx** [Fynx/BTech#4]
We need a volunteer to change this hack-rich poor solution. GraphicsMap should have a pointer to the object of class Map.

**Comment by szreder** [comment]
Work in progress in dev branch: already decoupled Grid from GraphicsMap and exposed some protected  interfaces in Map for the time being. Will work further after positive code review.

**Comment by Fynx** [comment]
Done. Some more work is required in Map / GraphicsMap though.
